### ISSUE TITLE
Move getCoords from predict to prepare_data

### ISSUE THREAD

**Issue by timcdlucas** [aknandi/disaggregation#11]
It's a slow bit and it'd be better if we only do it once.

**Comment by aknandi** [comment]
If you were predicting over the same space you were fitting the model that makes sense, but it would not work if you were predicting over newdata. Then you would still have to get the new coordinates to predict over. 

Not sure if we should then getPredCoords in prepare_data and use that in predict if(is.null(newdata)), but otherwise get the new coords. Or leave it as it is?

**Comment by timcdlucas** [comment]
I think the `if(is.null(newdata))` is the best option. But I guess this is pretty low priority now.
